name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build and push
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BROKER_SERVER: ${{ secrets.BROKER_SERVER }}
        run: |
        docker login --username manuelhernandezcarrasco --password $TOKEN ghcr.io
        docker build . --tag ghcr.io/manuelhernandezcarrasco/elec_dig:latest --build-arg DATABASE_URL=$DATABASE_URL --build-arg BROKER_SERVER=$BROKER_SERVER
        docker push ghcr.io/manuelhernandezcarrasco/elec_dig:latest
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_TAG,DATABASE_URL,BROKER_SERVER,TOKEN
          script: |
            for container_id in $(sudo docker ps -q); do sudo docker kill $container_id; done;
            for container_id in $(sudo docker images -q); do sudo docker rmi -f $container_id; done;
            sudo docker system prune --force
            sudo docker login --username manuelhernandezcarrasco --password $TOKEN ghcr.io
            sudo docker pull ghcr.io/manuelhernandezcarrasco/elec_dig:latest
            sudo docker run -d -p 8080:8080 ghcr.io/manuelhernandezcarrasco/elec_dig:latest
