name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Image
        run: |
          docker login --username manuelhernandezcarrasco --password ${{secrets.TOKEN}} ghcr.io
          docker build . -t ghcr.io/manuelhernandezcarrasco/elec_dig:latest --build-arg DATABASE_URL=${{secrets.DATABASE_URL}} --build-arg BROKER_SERVER=${{secrets.BROKER_SERVER}}
          docker push ghcr.io/manuelhernandezcarrasco/elec_dig:latest

  execute-commands:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: TOKEN
          script: |
            for container_id in $(sudo docker ps -q); do sudo docker kill $container_id; done;
            for container_id in $(sudo docker images -q); do sudo docker rmi -f $container_id; done;
            sudo docker system prune --force
            sudo docker login --username manuelhernandezcarrasco --password $TOKEN ghcr.io
            sudo docker pull ghcr.io/manuelhernandezcarrasco/elec_dig:latest
            sudo docker run -d -p 8080:8080 ghcr.io/manuelhernandezcarrasco/elec_dig:latest
